<a href="https://colab.research.google.com/github/ziyadshezoo/Testing/blob/main/intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np
import pandas as pd

In [11]:
print(np.random.rand(10))

[0.68733939 0.87452449 0.96133523 0.55962672 0.51403461 0.45528015
 0.47134023 0.99071668 0.99025224 0.81282375]


In [12]:
np.random.random(10)

array([0.863717  , 0.23156517, 0.18059711, 0.92462143, 0.45695445,
       0.87210728, 0.27332684, 0.13783333, 0.09967189, 0.41023417])

In [13]:
np.random.randint(0,100,5)

array([94, 45, 67, 51, 26])

In [14]:
a=np.array([])
a= np.random.randint(0,25,(5,5))
a=a.reshape(5,5)
np.random.shuffle(a)
aMax=a.max()
print(a,"\n",aMax)
print(a.argmin(),a.argmax())

[[20 13  2 14  8]
 [11 13  8  6 24]
 [ 4  9  1 14 12]
 [16 17 19 22  8]
 [ 5  9  8 11 22]] 
 24
12 9


In [15]:
 a1=np.ceil(2.5)
 a2=np.floor(2.5)
 a3=np.round(2.5)
 print(a1,a2,a3)

3.0 2.0 2.0


In [16]:
arr1=np.array([[1,2,3],[1,2,3],[5,3,9]])
arr2=np.array([[5,3,9],[1,2,3],[1,2,3]])


SyntaxError: ignored

In [23]:
l=['ahmed','mohamed','hello','ziyad']
l2=[1,2,3,4,5,6]
a=pd.Series(l2,index=['a','b','c','d','e','f'])
a

a    1
b    2
c    3
d    4
e    5
f    6
dtype: int64